# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Delete old main.pdf
        run: rm main.pdf
      - name: List files
        run: ls
      - name: Create test file
        run: touch test.py
      - name: Compile LaTeX document
        continue-on-error: true
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: luatex
          args: -interaction=nonstopmode -shell-escape
      - name: Check if pdf was created
        run: |
          OUTPUT=$(ls | grep "main.pdf")
          echo $OUTPUT
          if [ $OUTPUT == "main.pdf" ]; then
            echo "case 1"
          else
            echo "case 2"
          fi
          
          [ $OUTPUT == "main.pdf" ] && exit 0 || exit 1
      - name: Checkout compiled-pdf branch
        if: always()
        run: git switch compiled-pdf
      - name: List files
        if: always()
        run: ls
      - name: PWD
        if: always()
        run: pwd
      - name: Configure Git user
        run: | 
          git config --global user.name 'donovanclay'
          git config --global user.email 'donovan@donovanclay.com'
      - name: Commit new PDF file
        run: |
          current_date_time=$(date)
          git add main.pdf
          git commit -m "update main.pdf @ $current_date_time"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
