# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Delete old main.pdf
        run: rm main.pdf
      - name: Compile LaTeX document
        continue-on-error: true
        # uses: xu-cheng/latex-action@v3
        # with:
        #   root_file: main.tex
        #   compiler: luatex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
      - name: Check if pdf was created
        run: |
          OUTPUT=$(ls | grep "main.pdf")
          [ OUTPUT == "main.pdf" ] && exit 0 || exit 1
      - name: List Files
        # if: always()
        run: ls
      - name: PWD
        # if: always()
        run: pwd
      # - name: 
      # - name: Upload PDF to `compiled-pdf` branch
      #   uses: 
      # - name: Upload PDF
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     # # Name of the artifact to upload.
      #     # # Optional. Default is 'artifact'
      #     # name:
      
      #     # A file, directory or wildcard pattern that describes what to upload
      #     # Required.
      #     path: main.pdf
      
      #     # If true, an artifact with a matching name will be deleted before a new one is uploaded.
      #     # If false, the action will fail if an artifact for the given name already exists.
      #     # Does not fail if the artifact does not exist.
      #     # Optional. Default is 'false'
      #     overwrite: true
